public class NewCustomerCon {

    public PageReference Submit() {
        return null;
    }


    public OpportunityContactRole getRole() {
        return null;
    }


    public Opportunity getOpportunity() {
        return null;
    }


    public PageReference step3() {
        return null;
    }


    public PageReference step1() {
        return null;
    }


    public Contact getContact() {
        return null;
    }


    public Account getAccount() {
        return null;
    }


    public PageReference cancel() {
        return null;
    }


    public PageReference step2() {
        return null;
    }

}